### ISSUE TITLE
不能发送含有'&'的消息通知

### ISSUE THREAD

**Issue by doraemonkeys** [iKineticate/win-toast-notif-rs#3]
代码：
```rust
use win_toast_notify::*;

fn main() {
    WinToastNotify::new()
        // .set_app_id("Your App Name or App ID")    // 默认PowerShell，若输入系统不存在的AppID，则需使用fn set_notif_open("")，才可发送通知
        .set_notif_open("https://en.wikipedia.org/wiki/Li_Qingzhao")    // 点击通知的打开链接或文件(夹)
        .set_duration(Duration::Long)
        .set_title("《一剪梅·红藕香残玉簟秋》 宋·李清照")
        .set_messages(vec![
            "6&56"
        ])
        .set_logo(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\Li Qingzhao.jpeg", CropCircle::True)
        .set_image(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\yijianmei.jpg", ImagePlacement::Top)
        .set_actions(vec![
            Action {
                activation_type: ActivationType::Protocol,
                action_content: "阅读",
                arguments: "https://baike.baidu.com/item/%E4%B8%80%E5%89%AA%E6%A2%85%C2%B7%E7%BA%A2%E8%97%95%E9%A6%99%E6%AE%8B%E7%8E%89%E7%B0%9F%E7%A7%8B/593597#1",
                image_url: Some(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\read.png")
            },
            Action {
                activation_type: ActivationType::Protocol,
                action_content: "赏析",
                arguments: "https://baike.baidu.com/item/%E4%B8%80%E5%89%AA%E6%A2%85%C2%B7%E7%BA%A2%E8%97%95%E9%A6%99%E6%AE%8B%E7%8E%89%E7%B0%9F%E7%A7%8B/593597#4",
                image_url: Some(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\appreciation.png")
            }
        ])
        .set_audio(Audio::WinLoopingAlarm5, Loop::True)
        .show()
        .expect("Failed to show toast notification")
}
```

错误:
```rust
thread 'main' panicked at src\main.rs:30:10:
Failed to show toast notification: "Failed to execute command: ʹ�á�1�����������á�LoadXml��ʱ�����쳣:���쳣���� HRESULT:0xC00CE504��\r\n����λ�� ��:26 �\u{5b7}�: 13\r\n+             $XmlDocument.loadXml($xml)\r\n+             ~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : Exception\r\n \r\nʹ�á�1�����������á�Show��ʱ�����쳣:����������\r\n��������\r\n��\r\n����λ�� ��:28 �\u{5b7}�: 13\r\n+             [Windows.UI.Notifications.ToastNotificationManager, Windo ...\r\n+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : ArgumentException\r\n \r\n"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `D:\用户\computer\Downloads\win-toast-notify\examples\basic\target\debug\basic.exe` (exit code: 101)
```

可能是没有处理一些特殊字符的转义

**Comment by iKineticate** [comment]
> 代码：
> 
> ```rust
> use win_toast_notify::*;
> 
> fn main() {
>     WinToastNotify::new()
>         // .set_app_id("Your App Name or App ID")    // 默认PowerShell，若输入系统不存在的AppID，则需使用fn set_notif_open("")，才可发送通知
>         .set_notif_open("https://en.wikipedia.org/wiki/Li_Qingzhao")    // 点击通知的打开链接或文件(夹)
>         .set_duration(Duration::Long)
>         .set_title("《一剪梅·红藕香残玉簟秋》 宋·李清照")
>         .set_messages(vec![
>             "6&56"
>         ])
>         .set_logo(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\Li Qingzhao.jpeg", CropCircle::True)
>         .set_image(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\yijianmei.jpg", ImagePlacement::Top)
>         .set_actions(vec![
>             Action {
>                 activation_type: ActivationType::Protocol,
>                 action_content: "阅读",
>                 arguments: "https://baike.baidu.com/item/%E4%B8%80%E5%89%AA%E6%A2%85%C2%B7%E7%BA%A2%E8%97%95%E9%A6%99%E6%AE%8B%E7%8E%89%E7%B0%9F%E7%A7%8B/593597#1",
>                 image_url: Some(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\read.png")
>             },
>             Action {
>                 activation_type: ActivationType::Protocol,
>                 action_content: "赏析",
>                 arguments: "https://baike.baidu.com/item/%E4%B8%80%E5%89%AA%E6%A2%85%C2%B7%E7%BA%A2%E8%97%95%E9%A6%99%E6%AE%8B%E7%8E%89%E7%B0%9F%E7%A7%8B/593597#4",
>                 image_url: Some(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\appreciation.png")
>             }
>         ])
>         .set_audio(Audio::WinLoopingAlarm5, Loop::True)
>         .show()
>         .expect("Failed to show toast notification")
> }
> ```
> 
> 错误:
> 
> ```rust
> thread 'main' panicked at src\main.rs:30:10:
> Failed to show toast notification: "Failed to execute command: ʹ�á�1�����������á�LoadXml��ʱ�����쳣:���쳣���� HRESULT:0xC00CE504��\r\n����λ�� ��:26 �\u{5b7}�: 13\r\n+             $XmlDocument.loadXml($xml)\r\n+             ~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : Exception\r\n \r\nʹ�á�1�����������á�Show��ʱ�����쳣:����������\r\n��������\r\n��\r\n����λ�� ��:28 �\u{5b7}�: 13\r\n+             [Windows.UI.Notifications.ToastNotificationManager, Windo ...\r\n+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : ArgumentException\r\n \r\n"
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> error: process didn't exit successfully: `D:\用户\computer\Downloads\win-toast-notify\examples\basic\target\debug\basic.exe` (exit code: 101)
> ```
> 
> 可能是没有处理一些特殊字符的转义

好的，后面会排查一些特殊字符。

**Comment by iKineticate** [comment]
> 代码：
> ```rust
> use win_toast_notify::*;
> 
> fn main() {
>     WinToastNotify::new()
>         // .set_app_id("Your App Name or App ID")    // 默认PowerShell，若输入系统不存在的AppID，则需使用fn set_notif_open("")，才可发送通知
>         .set_notif_open("https://en.wikipedia.org/wiki/Li_Qingzhao")    // 点击通知的打开链接或文件(夹)
>         .set_duration(Duration::Long)
>         .set_title("《一剪梅·红藕香残玉簟秋》 宋·李清照")
>         .set_messages(vec![
>             "6&56"
>         ])
>         .set_logo(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\Li Qingzhao.jpeg", CropCircle::True)
>         .set_image(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\yijianmei.jpg", ImagePlacement::Top)
>         .set_actions(vec![
>             Action {
>                 activation_type: ActivationType::Protocol,
>                 action_content: "阅读",
>                 arguments: "https://baike.baidu.com/item/%E4%B8%80%E5%89%AA%E6%A2%85%C2%B7%E7%BA%A2%E8%97%95%E9%A6%99%E6%AE%8B%E7%8E%89%E7%B0%9F%E7%A7%8B/593597#1",
>                 image_url: Some(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\read.png")
>             },
>             Action {
>                 activation_type: ActivationType::Protocol,
>                 action_content: "赏析",
>                 arguments: "https://baike.baidu.com/item/%E4%B8%80%E5%89%AA%E6%A2%85%C2%B7%E7%BA%A2%E8%97%95%E9%A6%99%E6%AE%8B%E7%8E%89%E7%B0%9F%E7%A7%8B/593597#4",
>                 image_url: Some(r"C:\Users\11593\Documents\GitHub\win-toast-notify\examples\basic\src\appreciation.png")
>             }
>         ])
>         .set_audio(Audio::WinLoopingAlarm5, Loop::True)
>         .show()
>         .expect("Failed to show toast notification")
> }
> ```
> 
> 错误:
> ```rust
> thread 'main' panicked at src\main.rs:30:10:
> Failed to show toast notification: "Failed to execute command: ʹ�á�1�����������á�LoadXml��ʱ�����쳣:���쳣���� HRESULT:0xC00CE504��\r\n����λ�� ��:26 �\u{5b7}�: 13\r\n+             $XmlDocument.loadXml($xml)\r\n+             ~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : Exception\r\n \r\nʹ�á�1�����������á�Show��ʱ�����쳣:����������\r\n��������\r\n��\r\n����λ�� ��:28 �\u{5b7}�: 13\r\n+             [Windows.UI.Notifications.ToastNotificationManager, Windo ...\r\n+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : ArgumentException\r\n \r\n"
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> error: process didn't exit successfully: `D:\用户\computer\Downloads\win-toast-notify\examples\basic\target\debug\basic.exe` (exit code: 101)
> ```
> 
> 可能是没有处理一些特殊字符的转义

0.1.3已解决xml中的特殊字符
